---
- hosts: rcjweb
  vars_prompt:
    - name: "db_host"
      prompt: "MySQL Database Host"
      default: "localhost"
    - name: "db_user"
      prompt: "MySQL Database Username"
      default: root
    - name: "db_pass"
      prompt: "MySQL Database Password"
      private: yes
    - name: "sms_user"
      prompt: "SMS Broadcast Username"
      default: TEST
    - name: "sms_pass"
      prompt: "SMS Broadcast Password"
      private: yes
    - name: "sms_from"
      prompt: "SMS Sender Name"
      default: "RoboCupJnr"
    - name: "secret_salt"
      prompt: "Secret Salt"
      private: yes
  roles:
    - common
    - docker
    - role: mysql
      db_password: "{{ db_pass }}"
    # - role: soccer
    #   db_host: "{{ db_host }}"
    #   db_user: "{{ db_user }}"
    #   db_pass: "{{ db_pass }}"
    #   sms_user: "{{ sms_user }}"
    #   sms_pass: "{{ sms_pass ]}"
    #   sms_from: "{{ sms_from }}"
    #   secret_salt: "{{ secret_salt }}"
